#!/usr/bin/env python3
"""Generate include/fl_autopilot_commands.h — a scripted input session for
smoke-testing the whole UI without touching the keypad.

Butano's bn::core::init(keypad_commands) replays 2 chars per frame:
char[0] = '0' + (keys & 31), char[1] = '0' + (keys >> 5), with the GBA key
bit order (A=1, B=2, SELECT=4, START=8, RIGHT=16, LEFT=32, UP=64, DOWN=128).
When the string runs out, control returns to the real keypad.

Build the autopilot ROM with:
  make TARGET=feelo_ap BUILD=build_ap \
       USERFLAGS='-DBN_CFG_SPRITE_TILES_MAX_ITEMS=256 -DFL_AUTOPILOT'
"""

import os

KEY = {'A': 1, 'B': 2, 'SELECT': 4, 'START': 8,
       'RIGHT': 16, 'LEFT': 32, 'UP': 64, 'DOWN': 128}

# (frames, keys held during those frames)
SCRIPT = [
    (90, []),                    # home: clock + mascot render
    (2, ['A']), (10, []),        # -> mood pad
    (90, ['RIGHT', 'UP']),       # glide to top-right corner (PUMPED)
    (10, []),
    (150, ['LEFT', 'DOWN']),     # cross the whole pad (DRAINED), zone churn
    (10, []),
    (2, ['A']), (10, []),        # -> focus question
    (2, ['RIGHT']), (6, []),     # select 3rd -> 4th icon
    (2, ['RIGHT']), (6, []),     # -> 5th icon (LOST)
    (2, ['A']),                  # -> confirm: record is appended here
    (220, []),                   # celebrate anim + auto-return to home
    (2, ['SELECT']), (150, []),  # -> stats (text-heavy + sparkline)
    (2, ['B']), (60, []),        # back home
    (2, ['A']), (10, []),        # -> pad again
    (30, ['RIGHT']), (30, ['LEFT']),   # wiggle: value-text churn stress
    (30, ['RIGHT']), (30, ['LEFT']),
    (2, ['B']), (30, []),        # cancel back home (no record)
    (2, ['SELECT']), (60, []),   # stats once more
    (2, ['B']),                  # home; commands end -> real keypad
]


def main():
    chunks = []
    total = 0

    for frames, keys in SCRIPT:
        mask = 0
        for key in keys:
            mask |= KEY[key]
        chunk = (chr(ord('0') + (mask & 31)) + chr(ord('0') + (mask >> 5))) * frames
        chunks.append(chunk)
        total += frames

    commands = ''.join(chunks)
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    path = os.path.join(root, 'include', 'fl_autopilot_commands.h')

    with open(path, 'w') as f:
        f.write('// Generated by tools/gen_autopilot.py - do not edit by hand.\n')
        f.write('// Scripted input session (%d frames ~ %.1fs at 60fps).\n'
                % (total, total / 60))
        f.write('#ifndef FL_AUTOPILOT_COMMANDS_H\n#define FL_AUTOPILOT_COMMANDS_H\n\n')
        f.write('#include "bn_string_view.h"\n\n')
        f.write('namespace fl\n{\n\n')
        f.write('inline constexpr bn::string_view autopilot_commands =\n')
        for i in range(0, len(commands), 76):
            f.write('        "%s"\n' % commands[i:i + 76])
        f.write('        ;\n\n}\n\n#endif\n')

    print('wrote %s (%d frames, %d chars)' % (path, total, len(commands)))


if __name__ == '__main__':
    main()
